spring.datasource.url=jdbc:mysql://localhost:3306/Mas_db
spring.datasource.username=root
spring.datasource.password=Tarulata@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_Ss7dVslfyOs2t0
razorpay.key.secret=17jHMLrO88rDu6hsrAq7oKbz